# Generated by Django 6.0.4 on 2026-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='release_data',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
